//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSI_Checker_2p0.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSI_Checker_2p0.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI Checker v2.0.
        /// </summary>
        internal static string AppNameText {
            get {
                return ResourceManager.GetString("AppNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidir communcation.
        /// </summary>
        internal static string BidirMenuText {
            get {
                return ResourceManager.GetString("BidirMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsBypassRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsBypassRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU.
        /// </summary>
        internal static string CheckerControlBoardSettingsEcuText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsEcuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External source.
        /// </summary>
        internal static string CheckerControlBoardSettingsExternalSourceText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsExternalSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External src. relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsExtSrcRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsExtSrcRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsGainRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsGainRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board settings.
        /// </summary>
        internal static string CheckerControlBoardSettingsHeaderText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal source.
        /// </summary>
        internal static string CheckerControlBoardSettingsInternalSourceText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsInternalSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsLoadRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsLoadRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsOutputRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsOutputRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string CheckerControlBoardSettingsSensorText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsSensorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal relay.
        /// </summary>
        internal static string CheckerControlBoardSettingsSignalRelayText {
            get {
                return ResourceManager.GetString("CheckerControlBoardSettingsSignalRelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Pattern.
        /// </summary>
        internal static string CheckerControlLoadPatternText {
            get {
                return ResourceManager.GetString("CheckerControlLoadPatternText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure All.
        /// </summary>
        internal static string CheckerControlMeasureAllText {
            get {
                return ResourceManager.GetString("CheckerControlMeasureAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure From Selected.
        /// </summary>
        internal static string CheckerControlMeasureFromSelectedText {
            get {
                return ResourceManager.GetString("CheckerControlMeasureFromSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Selected.
        /// </summary>
        internal static string CheckerControlMeasureSelectedText {
            get {
                return ResourceManager.GetString("CheckerControlMeasureSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern selector.
        /// </summary>
        internal static string CheckerControlPatternSelectorText {
            get {
                return ResourceManager.GetString("CheckerControlPatternSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string CheckerControlPowerOnText {
            get {
                return ResourceManager.GetString("CheckerControlPowerOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit length.
        /// </summary>
        internal static string CheckerControlProtocolSettingsBitLengthText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsBitLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit rate.
        /// </summary>
        internal static string CheckerControlProtocolSettingsBitRateText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsBitRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Sum.
        /// </summary>
        internal static string CheckerControlProtocolSettingsCheckSumText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsCheckSumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Settings.
        /// </summary>
        internal static string CheckerControlProtocolSettingsHeaderText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync distance.
        /// </summary>
        internal static string CheckerControlProtocolSettingsSyncDistanceText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsSyncDistanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync type.
        /// </summary>
        internal static string CheckerControlProtocolSettingsSyncTypeText {
            get {
                return ResourceManager.GetString("CheckerControlProtocolSettingsSyncTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save location.
        /// </summary>
        internal static string CheckerControlSaveLocationSelectorText {
            get {
                return ResourceManager.GetString("CheckerControlSaveLocationSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor selector.
        /// </summary>
        internal static string CheckerControlSensorSelectorText {
            get {
                return ResourceManager.GetString("CheckerControlSensorSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog testing.
        /// </summary>
        internal static string CheckerMenuText {
            get {
                return ResourceManager.GetString("CheckerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DisabledText {
            get {
                return ResourceManager.GetString("DisabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string EnabledText {
            get {
                return ResourceManager.GetString("EnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed!.
        /// </summary>
        internal static string FailedInitializationText {
            get {
                return ResourceManager.GetString("FailedInitializationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start initialization.
        /// </summary>
        internal static string InitializationStartText {
            get {
                return ResourceManager.GetString("InitializationStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to PSI config file.
        /// </summary>
        internal static string InitPagePsiConfigPathText {
            get {
                return ResourceManager.GetString("InitPagePsiConfigPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the config file..
        /// </summary>
        internal static string InitPagePsiConfigPathTipText {
            get {
                return ResourceManager.GetString("InitPagePsiConfigPathTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from file.
        /// </summary>
        internal static string LoadText {
            get {
                return ResourceManager.GetString("LoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsMenuText {
            get {
                return ResourceManager.GetString("ResultsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe attenuation.
        /// </summary>
        internal static string ScopeAttenuationText {
            get {
                return ResourceManager.GetString("ScopeAttenuationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling.
        /// </summary>
        internal static string ScopeCouplingText {
            get {
                return ResourceManager.GetString("ScopeCouplingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpit Impedance.
        /// </summary>
        internal static string ScopeInputImpedanceText {
            get {
                return ResourceManager.GetString("ScopeInputImpedanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope setup.
        /// </summary>
        internal static string ScopeMenuText {
            get {
                return ResourceManager.GetString("ScopeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string ScopePowerButtonText {
            get {
                return ResourceManager.GetString("ScopePowerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input range.
        /// </summary>
        internal static string ScopeRangeText {
            get {
                return ResourceManager.GetString("ScopeRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenuText {
            get {
                return ResourceManager.GetString("SettingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital testing.
        /// </summary>
        internal static string SimulyzerMenuText {
            get {
                return ResourceManager.GetString("SimulyzerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test functions.
        /// </summary>
        internal static string TestMenuText {
            get {
                return ResourceManager.GetString("TestMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
