//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSI_Checker_2p0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class MeasurementSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MeasurementSettings defaultInstance = ((MeasurementSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MeasurementSettings())));
        
        public static MeasurementSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VoltageSync {
            get {
                return ((double)(this["VoltageSync"]));
            }
            set {
                this["VoltageSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VoltageTime {
            get {
                return ((double)(this["VoltageTime"]));
            }
            set {
                this["VoltageTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Setting2 {
            get {
                return ((double)(this["Setting2"]));
            }
            set {
                this["Setting2"] = value;
            }
        }
    }
}
